version: 2
jobs:
  build:
    docker:
      - image: sunslayer/latex-docker

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            apt update && apt install --no-install-recommends --yes \
                    $(cat .ci/build/make/dependencies/buster/apt.list)
            pip3 install --requirement .ci/build/make/dependencies/python.list

      - run:
          name: build packages
          command: make
