.PHONY: default
default: beamercolorthemewahoo.sty beamercolorthemewahoo.pdf

beamercolorthemewahoo.sty:
beamercolorthemewahoo.pdf: beamercolorthemewahoo.sty example.pdf | email.sty theme-doc.sty

example.pdf: beamercolorthemewahoo.sty

include ../../../../Makefile.mk
