name: build

on:
  pull_request:
    branches:
      - master
  push:
  workflow_dispatch:

jobs:
  make:
    runs-on: ubuntu-latest
    container: debian:${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - buster  # TeX Live 2018
          - bullseye  # TeX Live 2020
          - bookworm  # TeX Live 2022
    steps:
      - name: Install Git
        run: |
          apt update && apt install --no-install-recommends --yes \
              ca-certificates \
              git
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install dependencies
        run: |
          apt update && apt install --no-install-recommends --yes \
              $(cat .ci/build/make/dependencies/${{ matrix.os }}/apt.list)
      - name: make
        run: make --jobs=$(nproc) --output-sync
      - name: Archive artifacts
        if: ${{ matrix.os == 'bookworm' }}
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            **/*.zip
